/**
 * The Phase 1 shelf: fifty invented books, no database.
 *
 * The cover art is the coloured CSS shapes from the design canvas (docs/design/), so the grid
 * needs no network and no real covers. Titles, authors, blurbs and the two people are samples;
 * real covers arrive with the Open Library lookup in Phase 3.
 *
 * Numbers are from the Ofcom drama range and nothing else ever goes here (ADR 0005).
 * This whole file is thrown away in Phase 2, when items come from Neon (ADR 0004).
 */
import { type Item, itemSchema, type Profile, profileSchema } from "./schema";

/** The canvas draws six cover designs. There are exactly six, so the type says so. */
export type CoverVariant = 0 | 1 | 2 | 3 | 4 | 5;

/** Phase 1 only: which of the canvas's six cover designs to draw, in which two colours. */
export type MockCover = {
  bg: string;
  fg: string;
  variant: CoverVariant;
};

export type FixtureItem = Item & { mock: MockCover };

/** The signed-in person, until there is sign-in (Phase 2). */
export const VIEWER_ID = "p-priya";

export const PROFILES: Profile[] = [
  {
    id: "p-priya",
    first_name: "priya",
    whatsapp_number: "+447700900123",
    is_admin: false,
    invited_by: null,
    created_at: "2026-09-01T10:00:00Z",
  },
  {
    id: "p-sam",
    first_name: "sam",
    whatsapp_number: "+447700900456",
    is_admin: false,
    invited_by: null,
    created_at: "2026-09-02T10:00:00Z",
  },
].map((p) => profileSchema.parse(p));

function book(
  id: string,
  owner_id: string,
  title: string,
  author: string,
  blurb: string,
  genre: Item["genre"],
  age_band: Item["age_band"],
  status: Item["status"],
  reserved_by: string | null,
  reserved_at: string | null,
  bg: string,
  fg: string,
  variant: CoverVariant,
): FixtureItem {
  const item = itemSchema.parse({
    id,
    owner_id,
    kind: "book",
    isbn: null,
    title,
    author,
    blurb,
    genre,
    age_band,
    cover_url: null,
    photo_url: null,
    approx_count: null,
    status,
    reserved_by,
    reserved_at,
    collected_at: null,
    created_at: "2026-10-06T09:00:00Z",
  });
  return { ...item, mock: { bg: `#${bg}`, fg: `#${fg}`, variant } };
}

export const ITEMS: FixtureItem[] = [
  // picture books
  book(
    "b01",
    "p-priya",
    "The Lighthouse Mouse",
    "J. Alder",
    "A small mouse keeps the lamp lit through one long winter storm.",
    "picture books",
    "0-3",
    "available",
    null,
    null,
    "e9c46a",
    "264653",
    0,
  ),
  book(
    "b02",
    "p-sam",
    "Counting Clouds",
    "R. Penhale",
    "Ten shapes drift past a window before bedtime.",
    "picture books",
    "0-3",
    "available",
    null,
    null,
    "f4a261",
    "2a9d8f",
    1,
  ),
  book(
    "b03",
    "p-priya",
    "Blue Boat, Green Sea",
    "M. Okonkwo",
    "A paper boat goes further than anyone expected.",
    "picture books",
    "0-3",
    "available",
    null,
    null,
    "a8dadc",
    "1d3557",
    2,
  ),
  book(
    "b04",
    "p-sam",
    "Sunhat Summer",
    "T. Bramble",
    "The hat blows off on the hottest day of the year.",
    "picture books",
    "0-3",
    "available",
    null,
    null,
    "ffb703",
    "fb8500",
    4,
  ),
  book(
    "b05",
    "p-priya",
    "The Purple Door",
    "L. Vance",
    "Nobody on the street knows what is behind it.",
    "picture books",
    "4-6",
    "available",
    null,
    null,
    "cdb4db",
    "4a3b6b",
    0,
  ),
  book(
    "b06",
    "p-sam",
    "Fern and the Fox",
    "A. Quill",
    "They meet at the bottom of the garden, twice.",
    "picture books",
    "4-6",
    "available",
    null,
    null,
    "b7e4c7",
    "1b4332",
    5,
  ),
  book(
    "b07",
    "p-priya",
    "Pink Wellingtons",
    "S. Marley",
    "A puddle, a promise, and one lost boot.",
    "picture books",
    "4-6",
    "reserved",
    "p-sam",
    "2026-10-06T09:00:00Z",
    "ffafcc",
    "7b2d4f",
    2,
  ),
  book(
    "b08",
    "p-sam",
    "Night Swimming",
    "D. Hale",
    "The pool after dark belongs to somebody else.",
    "picture books",
    "4-6",
    "available",
    null,
    null,
    "8ecae6",
    "023047",
    3,
  ),
  book(
    "b09",
    "p-priya",
    "The Jam Thief",
    "P. Rowan",
    "Someone has been at the jars on the top shelf.",
    "picture books",
    "4-6",
    "available",
    null,
    null,
    "f28482",
    "f6bd60",
    1,
  ),
  book(
    "b10",
    "p-sam",
    "Pebble, Pebble",
    "N. Ash",
    "Counting stones along the whole length of a beach.",
    "picture books",
    "0-3",
    "available",
    null,
    null,
    "84a59d",
    "f5cac3",
    4,
  ),
  book(
    "b11",
    "p-priya",
    "The Bread Oven",
    "G. Mott",
    "The baker lets her watch, if she is up early enough.",
    "picture books",
    "4-6",
    "available",
    null,
    null,
    "fefae0",
    "bc6c25",
    5,
  ),
  book(
    "b12",
    "p-sam",
    "Acorn Weather",
    "H. Birch",
    "Everything the oak drops, and who comes for it.",
    "picture books",
    "4-6",
    "available",
    null,
    null,
    "dda15e",
    "283618",
    0,
  ),
  // early readers
  book(
    "b13",
    "p-sam",
    "Olive and the Long Walk",
    "K. Sparrow",
    "It is further to the shop than it looks on the map.",
    "early readers",
    "4-6",
    "available",
    null,
    null,
    "606c38",
    "fefae0",
    1,
  ),
  book(
    "b14",
    "p-priya",
    "Three Red Hens",
    "B. Castle",
    "One of them can open the latch.",
    "early readers",
    "4-6",
    "available",
    null,
    null,
    "e76f51",
    "f6e7c8",
    3,
  ),
  book(
    "b15",
    "p-sam",
    "The Kite String",
    "J. Moss",
    "Let go once and you will not get it back.",
    "early readers",
    "4-6",
    "available",
    null,
    null,
    "bde0fe",
    "2a4d8f",
    4,
  ),
  book(
    "b16",
    "p-priya",
    "Ned's Wobbly Tooth",
    "C. Prine",
    "Day six, and still hanging on.",
    "early readers",
    "4-6",
    "available",
    null,
    null,
    "ffd166",
    "073b4c",
    2,
  ),
  book(
    "b17",
    "p-sam",
    "The Rockpool Club",
    "E. Thorn",
    "Four children and everything the tide leaves behind.",
    "early readers",
    "7-9",
    "available",
    null,
    null,
    "06d6a0",
    "073b4c",
    5,
  ),
  book(
    "b18",
    "p-priya",
    "Marla Makes a Map",
    "V. Dunne",
    "Of her street, then the next one, then the whole town.",
    "early readers",
    "7-9",
    "available",
    null,
    null,
    "ef476f",
    "ffd166",
    0,
  ),
  book(
    "b19",
    "p-sam",
    "The Bus to Nowhere",
    "R. Keele",
    "The number 4 does not go where the timetable says.",
    "early readers",
    "7-9",
    "available",
    null,
    null,
    "118ab2",
    "ffd166",
    1,
  ),
  book(
    "b20",
    "p-priya",
    "Stone Soup Again",
    "I. Prosser",
    "The old trick, played on a village that has heard it.",
    "early readers",
    "4-6",
    "available",
    null,
    null,
    "f4a261",
    "264653",
    4,
  ),
  // chapter books
  book(
    "b21",
    "p-sam",
    "The Midnight Allotment",
    "W. Haddon",
    "Something is growing on plot eleven that nobody planted.",
    "chapter books",
    "7-9",
    "available",
    null,
    null,
    "0b132b",
    "f4d35e",
    5,
  ),
  book(
    "b22",
    "p-priya",
    "Twelve Grey Doors",
    "O. Frayne",
    "Eleven of them open onto a corridor.",
    "chapter books",
    "7-9",
    "available",
    null,
    null,
    "22223b",
    "f2e9e4",
    2,
  ),
  book(
    "b23",
    "p-sam",
    "The Quiet Twin",
    "M. Sayle",
    "One of them has not spoken since the move.",
    "chapter books",
    "7-9",
    "available",
    null,
    null,
    "9a8c98",
    "f2e9e4",
    0,
  ),
  book(
    "b24",
    "p-priya",
    "Harriet and the Hour Hand",
    "D. Pell",
    "The clock in the hall runs slow, on purpose.",
    "chapter books",
    "7-9",
    "available",
    null,
    null,
    "e9c46a",
    "264653",
    3,
  ),
  book(
    "b25",
    "p-sam",
    "The Lemon Orchard",
    "F. Navarro",
    "A summer with a grandmother who explains nothing.",
    "chapter books",
    "7-9",
    "available",
    null,
    null,
    "2a9d8f",
    "e9f5db",
    4,
  ),
  book(
    "b26",
    "p-priya",
    "Red Kite Hill",
    "A. Stanmore",
    "They come back to the same ridge every year.",
    "chapter books",
    "7-9",
    "available",
    null,
    null,
    "bc4749",
    "f2e8cf",
    1,
  ),
  book(
    "b27",
    "p-sam",
    "The Hollow Beech",
    "J. Ollerton",
    "You can stand inside it if you are small enough.",
    "chapter books",
    "7-9",
    "available",
    null,
    null,
    "386641",
    "f2e8cf",
    5,
  ),
  book(
    "b28",
    "p-priya",
    "Saltmarsh Summer",
    "L. Creed",
    "The path is only there for four hours a day.",
    "chapter books",
    "7-9",
    "reserved",
    "p-sam",
    "2026-10-06T09:00:00Z",
    "ffb4a2",
    "6d6875",
    2,
  ),
  book(
    "b29",
    "p-sam",
    "The Paper Lantern",
    "Y. Abe",
    "It is meant to be let go at the end of the festival.",
    "chapter books",
    "7-9",
    "available",
    null,
    null,
    "6d597a",
    "eaac8b",
    0,
  ),
  book(
    "b30",
    "p-priya",
    "Badger's Winter",
    "P. Lowther",
    "Nothing much happens, slowly, underground.",
    "chapter books",
    "7-9",
    "available",
    null,
    null,
    "3a5a40",
    "dad7cd",
    3,
  ),
  // fantasy and adventure
  book(
    "b31",
    "p-sam",
    "The Brass Compass",
    "E. Vane",
    "It points at whatever you have lost, not north.",
    "fantasy and adventure",
    "7-9",
    "available",
    null,
    null,
    "1d3557",
    "ffd166",
    5,
  ),
  book(
    "b32",
    "p-priya",
    "Nightforge",
    "R. Calloway",
    "The smiths work only between dusk and the first bell.",
    "fantasy and adventure",
    "10+",
    "available",
    null,
    null,
    "3c096c",
    "ff9e00",
    2,
  ),
  book(
    "b33",
    "p-sam",
    "The Tide Singer",
    "S. Marrow",
    "One voice holds the harbour back for three days.",
    "fantasy and adventure",
    "10+",
    "available",
    null,
    null,
    "14213d",
    "fca311",
    0,
  ),
  book(
    "b34",
    "p-priya",
    "Emberwood",
    "T. Strand",
    "The forest burns every hundred years and chooses who stays.",
    "fantasy and adventure",
    "10+",
    "available",
    null,
    null,
    "5f0f40",
    "fb8b24",
    4,
  ),
  book(
    "b35",
    "p-sam",
    "The Glass Ferry",
    "N. Hollis",
    "You can see the riverbed the whole way across.",
    "fantasy and adventure",
    "7-9",
    "reserved",
    "p-priya",
    "2026-10-06T09:00:00Z",
    "0f4c5c",
    "e36414",
    1,
  ),
  book(
    "b36",
    "p-priya",
    "Winter Crown",
    "A. Deverell",
    "A king who is only king while the lake is frozen.",
    "fantasy and adventure",
    "10+",
    "available",
    null,
    null,
    "2b2d42",
    "edf2f4",
    3,
  ),
  book(
    "b37",
    "p-sam",
    "The Last Cartographer",
    "M. Hale",
    "She is paid to leave places off the map.",
    "fantasy and adventure",
    "10+",
    "available",
    null,
    null,
    "540b0e",
    "e09f3e",
    5,
  ),
  book(
    "b38",
    "p-priya",
    "Saltwind",
    "B. Quinlan",
    "Three islands, one boat, and a crossing nobody makes twice.",
    "fantasy and adventure",
    "7-9",
    "available",
    null,
    null,
    "335c67",
    "fff3b0",
    2,
  ),
  book(
    "b39",
    "p-sam",
    "Thornfield Rising",
    "C. Agard",
    "The hedge has been moving towards the house for a year.",
    "fantasy and adventure",
    "10+",
    "available",
    null,
    null,
    "7209b7",
    "f72585",
    0,
  ),
  // science and nature
  book(
    "b40",
    "p-priya",
    "What Lives in the Hedge",
    "Dr P. Nandi",
    "Forty-one species between the pavement and the field.",
    "science and nature",
    "7-9",
    "available",
    null,
    null,
    "a7c957",
    "386641",
    3,
  ),
  book(
    "b41",
    "p-sam",
    "The Whale Road",
    "H. Sandell",
    "How a humpback finds the same bay every spring.",
    "science and nature",
    "7-9",
    "available",
    null,
    null,
    "219ebc",
    "023047",
    0,
  ),
  book(
    "b42",
    "p-priya",
    "Why the Sky Is",
    "J. Kettle",
    "The short answer, and then the long one.",
    "science and nature",
    "4-6",
    "available",
    null,
    null,
    "ffb703",
    "023047",
    4,
  ),
  book(
    "b43",
    "p-sam",
    "Puddles and Pondweed",
    "M. Reyes",
    "Everything you can find in water you could step over.",
    "science and nature",
    "4-6",
    "available",
    null,
    null,
    "8ecae6",
    "219ebc",
    1,
  ),
  book(
    "b44",
    "p-priya",
    "Seeds, Stems, Roots",
    "L. Oduya",
    "What a plant is doing while it appears to do nothing.",
    "science and nature",
    "7-9",
    "available",
    null,
    null,
    "ccd5ae",
    "606c38",
    5,
  ),
  book(
    "b45",
    "p-sam",
    "The Soil Beneath",
    "G. Faraday",
    "A teaspoon of it holds more living things than the street.",
    "science and nature",
    "10+",
    "available",
    null,
    null,
    "e9edc9",
    "bc6c25",
    2,
  ),
  // young adult
  book(
    "b46",
    "p-priya",
    "Nothing to Declare",
    "K. Imani",
    "A summer job at an airport, and a suitcase that is not hers.",
    "young adult",
    "10+",
    "available",
    null,
    null,
    "212529",
    "e9ecef",
    2,
  ),
  book(
    "b47",
    "p-sam",
    "The Long Platform",
    "R. Serrano",
    "He takes the last train every night and tells nobody why.",
    "young adult",
    "10+",
    "available",
    null,
    null,
    "6a040f",
    "faa307",
    0,
  ),
  book(
    "b48",
    "p-priya",
    "After the Lido",
    "T. Brennan",
    "The pool closed in August and the town has not recovered.",
    "young adult",
    "10+",
    "available",
    null,
    null,
    "03071e",
    "ffba08",
    5,
  ),
  book(
    "b49",
    "p-sam",
    "Signal Hill",
    "A. Mwangi",
    "One bar of reception and a message she cannot send.",
    "young adult",
    "10+",
    "available",
    null,
    null,
    "370617",
    "f48c06",
    3,
  ),
  book(
    "b50",
    "p-priya",
    "The Borrowed Coat",
    "S. Lindqvist",
    "It has somebody else's letters in the lining.",
    "young adult",
    "10+",
    "available",
    null,
    null,
    "cdb4db",
    "22223b",
    1,
  ),
];

export function profileById(id: string): Profile | undefined {
  return PROFILES.find((p) => p.id === id);
}

export function itemById(id: string): FixtureItem | undefined {
  return ITEMS.find((i) => i.id === id);
}
