/**
 * A password Rob can read out or paste into WhatsApp: four short words and three digits, like
 * `fox-lamp-river-otter-428`. Easy to type on a phone, and strong enough for a sign-in route
 * with no rate limit (ADR 0009): 200 words, four of them, and 900 numbers is about 2 × 10^12
 * possibilities, at tens of milliseconds of scrypt each.
 *
 * It is the person's password until Rob sets another: there is no change-password screen.
 */
const WORDS = [
  "acorn",
  "anchor",
  "apple",
  "apron",
  "arrow",
  "badger",
  "bagel",
  "banjo",
  "barley",
  "basket",
  "beacon",
  "beetle",
  "berry",
  "bison",
  "blanket",
  "bonnet",
  "bramble",
  "bridge",
  "bubble",
  "bucket",
  "button",
  "cabin",
  "cactus",
  "camel",
  "candle",
  "canoe",
  "carrot",
  "castle",
  "cedar",
  "cherry",
  "cloud",
  "clover",
  "cobble",
  "comet",
  "copper",
  "cotton",
  "cradle",
  "cricket",
  "crumpet",
  "daisy",
  "dingo",
  "dolphin",
  "donkey",
  "dragon",
  "drizzle",
  "duckling",
  "eagle",
  "ember",
  "falcon",
  "feather",
  "fennel",
  "ferret",
  "fiddle",
  "finch",
  "flint",
  "fossil",
  "fox",
  "garden",
  "gecko",
  "ginger",
  "goblin",
  "goose",
  "granite",
  "gravel",
  "harbour",
  "hazel",
  "hedgehog",
  "heron",
  "honey",
  "hoopoe",
  "ibis",
  "iceberg",
  "iris",
  "island",
  "ivory",
  "jackal",
  "jaguar",
  "jelly",
  "jigsaw",
  "juniper",
  "kayak",
  "kestrel",
  "kettle",
  "kiwi",
  "koala",
  "ladder",
  "lagoon",
  "lamp",
  "lantern",
  "lemon",
  "lentil",
  "lizard",
  "llama",
  "lobster",
  "magnet",
  "mango",
  "maple",
  "marble",
  "meadow",
  "melon",
  "mitten",
  "monkey",
  "moose",
  "mustard",
  "napkin",
  "nettle",
  "noodle",
  "nutmeg",
  "oboe",
  "olive",
  "onion",
  "orbit",
  "otter",
  "oyster",
  "paddle",
  "panda",
  "parrot",
  "parsley",
  "pebble",
  "pelican",
  "pencil",
  "penguin",
  "pepper",
  "pickle",
  "pigeon",
  "pirate",
  "plum",
  "poppy",
  "puddle",
  "puffin",
  "pumpkin",
  "quail",
  "quill",
  "rabbit",
  "radish",
  "raven",
  "ribbon",
  "river",
  "robin",
  "rocket",
  "saddle",
  "salmon",
  "sandal",
  "scarf",
  "seal",
  "shadow",
  "shell",
  "sparrow",
  "spoon",
  "squirrel",
  "stork",
  "sunset",
  "swallow",
  "teapot",
  "thimble",
  "thistle",
  "tiger",
  "toffee",
  "tortoise",
  "trumpet",
  "tulip",
  "tunnel",
  "turnip",
  "turtle",
  "umbrella",
  "velvet",
  "violet",
  "wagon",
  "walnut",
  "walrus",
  "wander",
  "weasel",
  "whale",
  "whisker",
  "willow",
  "window",
  "wombat",
  "yacht",
  "yellow",
  "zebra",
  "almond",
  "biscuit",
  "cobalt",
  "dandelion",
  "elm",
  "frost",
  "gull",
  "hamster",
  "jasmine",
  "kitten",
  "lupin",
  "magpie",
  "newt",
  "ocelot",
  "pansy",
  "quince",
  "rhubarb",
  "sorrel",
  "tadpole",
  "vole",
  "wren",
  "yarrow",
  "zinnia",
  "orchard",
] as const;

function pick<T>(items: readonly T[], random: () => number): T {
  const item = items[Math.floor(random() * items.length)];
  if (item === undefined) throw new Error("nothing to pick from");
  return item;
}

/** `random` returns a number in [0, 1). Pass one from crypto in the browser; Math.random in a test. */
export function onetimePassword(random: () => number): string {
  const words = Array.from({ length: 4 }, () => pick(WORDS, random));
  const digits = String(Math.floor(random() * 900) + 100);
  return `${words.join("-")}-${digits}`;
}

/** How many words there are to choose from, so a test can hold the strength to a number. */
export const WORD_COUNT = WORDS.length;

/** A source of randomness from the browser's crypto, in the shape onetimePassword wants. */
export function cryptoRandom(): number {
  const buf = new Uint32Array(1);
  crypto.getRandomValues(buf);
  return (buf[0] ?? 0) / 2 ** 32;
}
